//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Updater.Common {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L2Updater.Common.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking {0}/{1} files....
        /// </summary>
        public static string CheckingFiles {
            get {
                return ResourceManager.GetString("CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lineage executable not found, please perform new fullcheck..
        /// </summary>
        public static string GameExeNotFound {
            get {
                return ResourceManager.GetString("GameExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generating.
        /// </summary>
        public static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Input and output directories can&apos;t be equals.
        /// </summary>
        public static string InputAndOutputAreEquals {
            get {
                return ResourceManager.GetString("InputAndOutputAreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Patch cancelled!.
        /// </summary>
        public static string PatchCanceled {
            get {
                return ResourceManager.GetString("PatchCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lineage2Shield Patch Generator.
        /// </summary>
        public static string PatchGeneratorAppTitle {
            get {
                return ResourceManager.GetString("PatchGeneratorAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Manually closed file check.
        /// </summary>
        public static string PatchingProcessCanceled {
            get {
                return ResourceManager.GetString("PatchingProcessCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Patch process has been started.
        /// </summary>
        public static string PatchingProcessStarted {
            get {
                return ResourceManager.GetString("PatchingProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your patch is ready.
        /// </summary>
        public static string PatchReady {
            get {
                return ResourceManager.GetString("PatchReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start create your patch.
        /// </summary>
        public static string StartPatchGenerate {
            get {
                return ResourceManager.GetString("StartPatchGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total: {0} files processed.
        /// </summary>
        public static string TotalFilesProcessed {
            get {
                return ResourceManager.GetString("TotalFilesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updater is already open.
        /// </summary>
        public static string UpdaterAlreadyOpen {
            get {
                return ResourceManager.GetString("UpdaterAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updater Lineage2Shield.
        /// </summary>
        public static string UpdaterAppTitle {
            get {
                return ResourceManager.GetString("UpdaterAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version check stopped manually.
        /// </summary>
        public static string VersionCheckedStoppedManually {
            get {
                return ResourceManager.GetString("VersionCheckedStoppedManually", resourceCulture);
            }
        }
    }
}
